### PR TITLE
New tools and examples

### PR DESCRIPTION
**Pull request by jongrumer**
New tools:
- fical:  a tool for computing line frequency isotope shift parameters and/or energies using output files from ris4
- mithit: support (matlab) routines for rhfszeeman (hyperfine/Zeeman eigenstates, transition properties)

New/updated grasp examples (associated to the new manual):
- grasptests/

### CODE REVIEW

**Comment by jongrumer** [comment]
@mortenpi Something odd is going on with the makedocs.sh doxygen script - could you send some aid in my direction?

**Comment by mortenpi** [comment]
I have a hunch that it maybe just runs out of memory? Does it work locally?

**Comment by jongrumer** [comment]
> I have a hunch that it maybe just runs out of memory? Does it work locally?

The problem is the matlab scripts that are now included in src/tools/mithit:
```bash
Parsing code for file src/lib/mpi90/sys_getwd_I.f90...
Parsing code for file src/lib/mpi90/sys_mkdir.f90...
Parsing code for file src/lib/mpi90/sys_mkdir_I.f90...
Parsing code for file src/tool/mithit/gaussplot.m...
./makedocs.sh: line 10: 204786 Segmentation fault      (core dumped) doxygen
ERROR: Doxygen failed with 139
```
do you know how to quickly fix this (yes, I would be very grateful ;)) ? Otherwise I'll do my own debugging...

**Comment by mortenpi** [comment]
For what it's worth, it seems like it's a bug in Doxygen 1.8. I grabbed the latest master (1.9.3) and it is able to also index the Matlab files:

image

Unfortunately, it doesn't look there is an easy way to get an updated version via `apt`, but [they do distribute precompiled Doxygen binaries for Linux](https://www.doxygen.nl/download.html), so we could change our CI over to those if we want.

**Pull request merged**
