### PR TITLE
Improve handling of MPI_TMP in cpath

### PR DESCRIPTION
**Pull request by mortenpi**
`cpath` has an arbitrary limit of 64 characters for the length of the `MPI_TMP` environment variable. What is worse, if the variable is longer than that, `cpath` will fall back to the default `/scratch/$USER` value, instead of throwing an error.

With this patch, the original arbitrary limit is removed and the helper function `getenv_allocating` will just allocate the necessary amount of memory to store the value of the variable.

There is still an arbitrary limit -- 128 characters, imposed by via the `lendisk0` variable to the disk variable. `disk` is the variable used to propagate the value to slave nodes, and fixing the length handling there is beyond the scope of this patch.

### CODE REVIEW

**Comment by cffischer** [comment]
Seems reasonable to me.

**Comment by jongrumer** [comment]
Should we just merge this @mortenpi @cffischer? I don't feel knowledgable enough to make a justified decision here, at least not without dedicating some time (which I don't have at the moment hehe).

**Comment by mortenpi** [comment]
It's a relatively straightforward fix, but I did mark this as a draft PR. Possibly because I wanted to add a test for it, but I don't remember exactly. I'll aim to go through this PR again some time in the next 2 weeks to make sure it hasn't gone stale and then we can merge it.

**Comment by mortenpi** [comment]
I believe this is good to go now.

I added some tests as well, which also act as simple integration tests (they call `rnucleus`, `rcsfgenerate`, `rwfnestimate`, `rangular` and `rmcdhf`, including both the serial and MPI versions). It also tests the long `MPI_TMP` case, and I made sure that the test fails if you run it on the current master without this patch. The tests do not check the _content_ of the output, just that all the programs exit with zero exit codes and produce the necessary output files.

**Comment by jongrumer** [comment]
Aight, I'm gonna merge this as well now. The first env variable fix seems ok to me, and the integration test is less crucial but also seems fine!

**Pull request merged**
