### PR TITLE
rmixextract -- serious big fix (Gaigalas)

### PR DESCRIPTION
**Pull request by jongrumer**
### Update of `rmixextract` - by G. Gaigalas (March-April, 2022).

Idea: extraction of CSF's if a mixing coefficient is larger than a given cut-off value.
This was previously done for across all eigenstates together - i.e. if the mixing coeff. for
a given CSF was larger than the cut-off in any of the eigenstates, it was extracted. Now, 
a second option will be added where this can be done also for each eigenstate separately.
This facilitates e.g. extractions of CSF's for more problematic eigenstates, i.e. you can weight your
calculation to include more important interactions for the more challenging eigenstates.

### Original patch description files (from GG)
The attached files with output from the OLD and NEW versions illustrate the issues.
- [script_rmixextract.txt](https://github.com/compas/grasp/files/8420908/script_rmixextract.txt)
- [Output_script_rmixextract_OLD.txt](https://github.com/compas/grasp/files/8420900/Output_script_rmixextract_OLD.txt)
- [Output_script_rmixextract.txt](https://github.com/compas/grasp/files/8420901/Output_script_rmixextract.txt)

### Appendix (save for now, use in documentation later):
```
OLD 

E(1) =  a(11) CSF(11) + a(12) CSF (12) + a(13) CSF (13) + ... + a(1n) CSF (1n)  | limit > 0,001
E(2) =  a(21) CSF(21) + a(22) CSF (22) + a(23) CSF (13) + ... + a(2m) CSF (2m)  | limit > 0,001
...
E(k) =  a(k1) CSF(k1) + a(k2) CSF (k2) + a(k3) CSF (k3) + ... + a(kn) CSF (kl)  | limit > 0,001

output > for each E 

CSF(11) CSF (12) CSF (13)  ... CSF (1n) ... CSF(k1) CSF (k2) CSF (k3)  ... CSF (kl)

=========================================================================================
NEW

E(1) =  a(11) CSF(11) + a(12) CSF (12) + a(13) CSF (13) + ... + a(1n) CSF (1n)  | limit > 0,001
E(2) =  a(21) CSF(21) + a(22) CSF (22) + a(23) CSF (13) + ... + a(2m) CSF (2m)  | limit > 0,001
...
E(k) =  a(k1) CSF(k1) + a(k2) CSF (k2) + a(k3) CSF (k3) + ... + a(kn) CSF (kl)  | limit > 0,001

output > for ech E(1) 

CSF(11) CSF (12) CSF (13)  ... CSF (1n)

output > for ech E(2) 

CSF(21) CSF (22) CSF (23)  ... CSF (2m)

output > for ech E(k) 

CSF(k1) CSF (k2) CSF (k3)  ... CSF (kl)

=========================================================================================
```

### CODE REVIEW

**Review by mortenpi — APPROVED** [review]
Can't comment on the correctness of the changes themselves, but LGTM from a git-technical point of view.

**Comment by jongrumer** [comment]
Great, thanks @mortenpi! Aren't you busy with your thesis? ;)

Yes, about if the method changes are correct or not - I fully trust @gaigalas here.

Thanks again, I'll merge this later today already I think, since it is a quite urgent bug to get fixed.

**Comment by cffischer** [comment]
I think this is an example where some clear documentation is needed as to how the exctraction is performed.  Is it done independently for each block, one at a time,  or more universally over all expansions on the basis of some weighted average.

**Comment by jongrumer** [comment]
@gaigalas Do you mind sending a few sentences about how the code operates now - properly, as you see it? Just to help me and the rest of the community of users understand what goes on. I.e. with regards to if the extraction is carried out independently for each block, one at a time, or more universally over all expansions on the basis of some weighted average? We can then perhaps add a few sentences about this in the manual or elsewhere, just to keep each code, at least, briefly, documented.

Would be much appreciated! Thanks! /Jon

**Comment by gaigalas** [comment]
@jon Can we Skype and I will tel you.

Best wishes,
Gediminas

**Comment by jongrumer** [comment]
@gaigalas Ok, I'll will send you an email with a skype-link!

**Comment by jongrumer** [comment]
**Update:** Me and Gediminas have agreed to update the code to either extract CSF's based on all eigenstates, or separately for each given eigenstate. This allows for the code to be used for both e.g. production of multireferences (via the option: across all eigenstates) or to e.g. extract additional CSF's for some given more problematic eigenstates (via the option: separate extraction for each individual state). Gedminas is working on this now.

**Pull request closed without merging**
