### PR TITLE
CFF autumn patches -  update no 1 - rnucleus

### PR DESCRIPTION
**Pull request by jongrumer**
A new F90 version of rnucleus submitted by @cffischer (autumn 2019). This version includes a data module of values tabulated by Angeli et al.  which has now been incorporated it into the GRASP rnucleus (geniso) application. 

She highlights additional future updates:
- the nucleus application should not define the **grid**, but should be performed by a separate module.
-  the code is overall written in an old-fashioned manner, and should be updated to according to modern fortran practices.
- Some routines like `ESTRMS` and `GETCPR` based on work by Farid and Mohanty that may be totally out-of-date.  She notes that such programs should also be in the `nucleus_m.f90` module, but that they might not be part of the current standard (?) and consequently did move them.

Quick comparisons of old and new version (shows the impact on parameter c):
```
OLD                                                             NEW
---------------------------------------------                   ---------------------------------------------
Z = 57 (Lanthanum)
-------------------------------------------------------------------------------------------------------------
Atomic number:                                                  Atomic number:
   57.000000000000000                                              57.000000000000000
Mass number (integer) :                                         Mass number (integer) :
   139.00000000000000                                              139.00000000000000
Fermi distribution parameter a:                                 Fermi distribution parameter a:
  0.52338755531043146                                             0.52338755531043146
Fermi distribution parameter c:                                 Fermi distribution parameter c:
   5.8066716284034845                                         |    5.7425242686940825                      < -----
Mass of nucleus (in amu):                                       Mass of nucleus (in amu):
   138.87420094552900                                              138.87420094552900
Nuclear spin (I) (in units of h / 2 pi):                        Nuclear spin (I) (in units of h / 2 pi):
   1.0000000000000000                                              1.0000000000000000
Nuclear dipole moment (in nuclear magnetons):                   Nuclear dipole moment (in nuclear magnetons):
   1.0000000000000000                                              1.0000000000000000
Nuclear quadrupole moment (in barns):                           Nuclear quadrupole moment (in barns):
   1.0000000000000000                                              1.0000000000000000
-------------------------------------------------------------------------------------------------------------

Z = 92 (Uranium)
-------------------------------------------------------------------------------------------------------------
Atomic number:                                                  Atomic number:
   92.000000000000000                                              92.000000000000000
Mass number (integer) :                                         Mass number (integer) :
   238.00000000000000                                              238.00000000000000
Fermi distribution parameter a:                                 Fermi distribution parameter a:
  0.52338755531043146                                             0.52338755531043146
Fermi distribution parameter c:                                 Fermi distribution parameter c:
   6.9865189068053173                                         |    7.1321507915792086                      < -----
Mass of nucleus (in amu):                                       Mass of nucleus (in amu):
   237.97844064892399                                              237.97844064892399
Nuclear spin (I) (in units of h / 2 pi):                        Nuclear spin (I) (in units of h / 2 pi):
   1.0000000000000000                                              1.0000000000000000
Nuclear dipole moment (in nuclear magnetons):                   Nuclear dipole moment (in nuclear magnetons):
   1.0000000000000000                                              1.0000000000000000
Nuclear quadrupole moment (in barns):                           Nuclear quadrupole moment (in barns):
   1.0000000000000000                                              1.0000000000000000
-------------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by mortenpi** [comment]
Should we merge this?

**Comment by cffischer** [comment]
Merge OK.   Maybe merging in steps is OK.

**Review by mortenpi — APPROVED** [review]
Brought this up to speed with the latest master. If the CI passes, then we can merge this as far as I am concerned.

**Comment by jongrumer** [comment]
Alright, this one is long overdue. Seems to work fine as far as I can tell from som additional testings just now. 

I'll merge now then!

**Pull request merged**
